const ErrorsEnum = {
  ROUTING_ERROR: 1,
  INVALID_TYPE_ERROR: 2,
  DATABASE_ERROR: 3,
  NOT_FOUND_ERROR: 4,
  AUTHENTICATION_ERROR: 5,
  AUTHORIZATION_ERROR: 6,
  INTERNAL_SERVER_ERROR: 7
}

export default ErrorsEnum;